name: firmata
version: 0.4.0-dev
description: Dart Implementation of Firmata
author: Nicolas Francois  <nicolas.franc@gmail.com>
homepage: https://github.com/nfrancois/firmata
environnment:
  sdk: '>=1.9.1 <2.0.0'
dependencies:
  serial_port: ">=0.3.0 <1.0.0"
  chrome: ">=0.6.5 <0.7.0"
  gpio_commons: ">=0.1.0 <0.2.0"
dev_dependencies:
  grinder: ">=0.7.2 <0.8.0"
  ccompile: ">=0.2.10 <0.3.0"
  test: ">=0.12.3 <0.13.0"
  dart_coveralls: ">=0.4.0 <0.5.0"
  dartdoc: ">=0.0.1+10 <0.1.0"
